spring.application.name=task_management

spring.datasource.url=jdbc:postgresql://localhost:5432/tasks_management
spring.datasource.username=kiran
spring.datasource.password=Kiran@12345
logging.level.org.springframework.security=DEBUG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret = 0q9joingevfs8c7gb v2r9ef0sdq-vc 0yf8vug refsc0a9rff8v3yi

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=user-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
debug=true